travis:
  secure:
    BINSTAR_TOKEN: Y0HNv6XSJces+LO2JPc5/icu9QaQdZh/YSa7HgWEEV6i8obci3NHRhWSaLoLFxY8bkaZ27bNYG+c1QrSgVRL2aG8nlnepz7nBPa4EDqMHir2JVjsWEC/gnNHdmTh3oQ+4NvLX3l0Ocj6x+3RD2f9C35TKbR18G2+3kavJjisRcjanutSnT7s3GMsOzO1YsZ1YQ93TKMMK9p8MePaQ0v2giWlcf5IUdFo70Is85tzhRIJly03gWZVu0x+BS3eCohyHD0f4eLp3CAKj7ZzHtfRUjKBaf3VZ05qdyzC3qzEMTMzzcOGA6/bfryRfilBSsylIeCJ2rUs3sE5tQRe3uRto7ghkvXDKnOtdaAYzdxKZA+M+iRTZw5zXfSXGKbZGiGk9zzX/3cvhppw3PSGAP+6hdA3EZMLD0XDFX1PVCRRLE8ApYLCWI5aX9+hS9cIitdEzmWezpkqODgg3i+nV3ViX6OKsPkrjwr+T/mPCjZWUHJIogCyBtjaSr3szDHkdsBi5gtdXOittyvCFlNe2meoepPiMbHpG9bRW0V+ggemSCc/BdRxu+rNjARsi2okfwplDk1luiJLDZ8YTn90bpUQTcZhkyxx0MYvifUrjDU5BthPIWPK2GIGXTTzRVUP0QIIoHddNqK3MRMxYu6E3kzC9sESpHm+jScE4l+efDb5J7I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
